### ISSUE TITLE
Broken links

### ISSUE THREAD

**Issue by pavelbinar** [posty72/posty.co.nz#11]
Hi I found the two broken links at your page:

"wrote about dropping the CMS." `http://www.posty.co.nz/development/2015/12/11/breaking-away-from-the-cms.html`

at the page: https://posty.co.nz/cms-vs-static-performance-review/

And `https://posty.co.nz/turn-old-media-studies-assignments-into-art/images/ResizedImage701635-starchy-dutch-screenshot-3.gif` at https://posty.co.nz/turn-old-media-studies-assignments-into-art/

Cheers!

**Comment by posty72** [comment]
Resolved in https://github.com/posty72/posty.co.nz/pull/13

**Comment by pavelbinar** [comment]
no worries
